# Generated by Django 3.2.7 on 2021-10-01 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0003_auto_20211001_1436"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generaldetails",
            name="Address",
        ),
        migrations.RemoveField(
            model_name="generaldetails",
            name="Bio",
        ),
        migrations.RemoveField(
            model_name="generaldetails",
            name="Mobile",
        ),
        migrations.RemoveField(
            model_name="generaldetails",
            name="Name",
        ),
        migrations.AddField(
            model_name="generaldetails",
            name="address",
            field=models.TextField(default="Pithapur", verbose_name="Address"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generaldetails",
            name="bio",
            field=models.TextField(default="Software Developer", verbose_name="Bio"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generaldetails",
            name="mobile",
            field=models.CharField(
                default="+91 7978928490",
                help_text="Format: +(1-3) (9-13)",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\+(9[976]\\d|8[987530]\\d|6[987]\\d|5[90]\\d|42\\d|3[875]\\d|2[98654321]\\d|9[8543210]|8[6421]\\\n|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1) \\d{1,14}$",
                        "Invalid format! Format: +(1-3) (9-13)",
                    )
                ],
                verbose_name="Mobile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generaldetails",
            name="name",
            field=models.CharField(
                default="Rohnak Agarwal", max_length=120, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
