# Generated by Django 3.2.7 on 2021-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_generaldetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldetails',
            name='bio',
            field=models.TextField(max_length=150, verbose_name='Bio'),
        ),
    ]
