# Generated by Django 3.2.7 on 2021-10-03 03:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("details", "0009_rename_technicaldetailsotherurls_technicaldetailsextraurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "educational_level",
                    models.CharField(max_length=120, verbose_name="Education Level"),
                ),
                (
                    "institute_name",
                    models.CharField(max_length=150, verbose_name="Institute Name"),
                ),
                (
                    "institute_address",
                    models.TextField(null=True, verbose_name="Institute Address"),
                ),
                (
                    "year_of_admission",
                    models.IntegerField(null=True, verbose_name="Year of admission"),
                ),
                (
                    "year_of_passing",
                    models.IntegerField(verbose_name="Year of passing"),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0.00 - 100.00",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Percentage",
                    ),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0.00 - 10.00",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="Grade Points Average (CGPA)",
                    ),
                ),
                ("major_subject", models.CharField(max_length=120, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
