# Generated by Django 3.2.7 on 2021-10-03 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("details", "0011_alter_educationaldetails_institute_address"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EducationalDetails",
            new_name="EducationalDetail",
        ),
        migrations.RenameModel(
            old_name="GeneralDetails",
            new_name="GeneralDetail",
        ),
        migrations.RenameModel(
            old_name="TechnicalDetails",
            new_name="TechnicalDetail",
        ),
    ]
