# Generated by Django 3.2.7 on 2021-10-03 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0012_auto_20211003_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationaldetail",
            name="cgpa",
            field=models.DecimalField(
                decimal_places=2,
                help_text="0.00 - 10.00",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Cumulative Grade Points Average (CGPA)",
            ),
        ),
    ]
