# Generated by Django 3.2.7 on 2021-10-03 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("details", "0013_alter_educationaldetail_cgpa"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="educationaldetail",
            unique_together={("user", "educational_level")},
        ),
    ]
