# Generated by Django 3.2.7 on 2021-10-04 14:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("details", "0014_alter_educationaldetail_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generaldetail",
            name="mobile",
            field=models.CharField(
                help_text="Format: +(1-3) (9-13)",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\+(9[976]\\d|8[987530]\\d|6[987]\\d|5[90]\\d|42\\d|3[875]\\d|2[98654321]\\d|9[8543210]|8[6421]\\\n|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1) \\d{1,14}$",
                        "Invalid format! Format: +(1-3) (9-13)",
                    )
                ],
                verbose_name="Mobile",
            ),
        ),
        migrations.CreateModel(
            name="ExperienceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience_type",
                    models.CharField(
                        choices=[("job", "Job"), ("internship", "Internship")],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(null=True, verbose_name="End Date")),
                (
                    "institute_name",
                    models.CharField(max_length=150, verbose_name="Institute Name"),
                ),
                (
                    "institute_address",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Institute Address"
                    ),
                ),
                (
                    "reference_person_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Reference Person Name"
                    ),
                ),
                (
                    "reference_person_mobile",
                    models.CharField(
                        help_text="Format: +(1-3) (9-13)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\+(9[976]\\d|8[987530]\\d|6[987]\\d|5[90]\\d|42\\d|3[875]\\d|2[98654321]\\d|9[8543210]|8[6421]\\\n|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1) \\d{1,14}$",
                                "Invalid format! Format: +(1-3) (9-13)",
                            )
                        ],
                        verbose_name="Reference Person Mobile",
                    ),
                ),
                ("skills", models.TextField(null=True, verbose_name="Skills")),
                (
                    "document_url",
                    models.URLField(null=True, verbose_name="Document URL"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
