# Generated by Django 3.2.7 on 2021-10-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0015_auto_20211004_2006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experienceitem",
            name="experience_type",
            field=models.CharField(
                choices=[("job", "Job"), ("internship", "Internship")],
                default="job",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
