# Generated by Django 3.2.7 on 2021-10-06 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("details", "0016_alter_experienceitem_experience_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(max_length=120, verbose_name="Skill Name"),
                ),
                (
                    "skill_level",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Average"),
                            (3, "Good"),
                            (4, "Verygood"),
                            (5, "Excellent"),
                        ],
                        verbose_name="Skill Level",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
