# Generated by Django 3.2.7 on 2021-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0017_skillitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillitem",
            name="skill_level",
            field=models.IntegerField(
                choices=[
                    (1, "Poor"),
                    (2, "Average"),
                    (3, "Good"),
                    (4, "Very Good"),
                    (5, "Expert"),
                ],
                verbose_name="Skill Level",
            ),
        ),
    ]
